create table produto_und (
	id              	integer generated by default as identity,    
    und             	varchar(10) not null,
    descricao			varchar(50) not null,
    primary key (id)
);    

create table produto_grupo (
	id                  integer generated by default as identity,        
    descricao           varchar(50) not null,
    primary key (id)
);

create table produto (
	id                  integer generated by default as identity,        
    codigo_barras       varchar(14),
    descricao           varchar(100) not null,
    id_und              integer not null,
    id_grupo            integer not null,
    qtd_minima          numeric(15, 3) default 0,
    qtd_maxima          numeric(15, 3) default 0,
	qtd_estoque         numeric(15, 3) default 0,
    valor_custo         numeric(15, 2) default 0,
    valor_venda         numeric(15, 2) default 0,
	obs 				blob sub_type 1 segment size 8192,  
    photo               blob sub_type 0 segment size 80,     
	ativo               smallint default 1 check (ativo in (0, 1)),
	created_at          timestamp default current_timestamp, 
	updated_at          timestamp default current_timestamp, 
    primary key (id),
	foreign key (id_und) references produto_und (id),
    foreign key (id_grupo) references produto_grupo (id)
);

create table pessoa (
	id 					integer generated by default as identity, 
	cpf_cnpj            varchar(14),
	nome_razao          varchar(70) not null,
	apelido_fantasia    varchar(50),
	logradouro          varchar(70), 
	numero              varchar(10),
	complemento         varchar(35),
	bairro              varchar(35),
	cep                 char(8),
	municipio           varchar(35),
	uf                  char(2),  
	created_at          timestamp default current_timestamp, 
	updated_at          timestamp default current_timestamp,
	primary key (id)
);

create table tipo_contato (
	id 					integer generated by default as identity, 
	descricao           varchar(35) not null,
	primary key (id)
);	

create table pessoa_contato (
	id 					integer generated by default as identity, 
	id_pessoa			integer not null,
	id_tipo             integer not null,
	contato             varchar(50) not null,
	primary key (id),
	foreign key (id_pessoa) references pessoa (id) on delete cascade,
	foreign key (id_tipo) references tipo_contato (id)
);

